language: java
jdk:  
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
install: true
script:
  - mvn clean install "-Dgpg.signature.skip=$GPG_SIGNATURE_SKIP"
  - |
    mvn sonar:sonar \
      "-Dsonar.projectKey=$SONAR_PROJECT_KEY" \
      "-Dsonar.organization=$SONAR_ORGANIZATION_KEY" \
      "-Dsonar.host.url=$SONAR_URL" \
      "-Dsonar.login=$SONAR_TOKEN"