language: java
jdk:  
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
install: true
script:
  - mvn clean install "-Dgpg.signature.skip=$GPG_SIGNATURE_SKIP"